export interface PhotographyCategory {
  category: string;
  images: string[];
}

export const photographyData: PhotographyCategory[] = [
  {
    category: 'EDITORIALS',
    images: [
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed1.JPG',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed2.JPG',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed3.JPG',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed4.JPG',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed5.JPG',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed6.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed7.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed8.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed9.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed10.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed11.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed12.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed13.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed14.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed15.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed16.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed17.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed18.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed19.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed20.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed21.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed22.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed23.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed24.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed25.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed26.jpeg',
    ],
  },
  // {
  //   category: 'PHOTOGRAPHY',
  //   images: [
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p1.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p2.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p3.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p4.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p5.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p6.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p7.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p8.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p9.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p10.jpeg',
  //   ],
  // },
  {
    category: 'SET DESIGN',
    images: [
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd1.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd2.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd3.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd4.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd5.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd6.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd7.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd8.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd9.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd10.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd12.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd13.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd14.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd15.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd16.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd17.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd18.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd19.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd20.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd21.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd22.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd23.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd24.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd25.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd26.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd27.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd28.jpeg',
    ],
  },
];
