export interface PhotographyCategory {
  category: string;
  images: string[];
}

export const photographyData: PhotographyCategory[] = [
  {
    category: 'EDITORIALS',
    images: [
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_1.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_2.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_3.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_4.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_5.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_6.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_7.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_8.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_9.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_10.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_11.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_12.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_13.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_14.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_15.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_16.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_17.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_18.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_19.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_20.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_21.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_22.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_23.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_24.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_25.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_26.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_27.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_28.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_29.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_30.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_31.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_32.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_33.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_34.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_35.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_36.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_37.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_39.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_40.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_42.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_43.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_44.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_45.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_46.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_47.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_48.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_49.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_50.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_51.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_52.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_53.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_54.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_55.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/editorials_x/ed_56.jpeg',
    ],
  },
  // {
  //   category: 'PHOTOGRAPHY',
  //   images: [
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p1.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p2.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p3.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p4.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p5.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p6.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p7.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p8.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p9.jpeg',
  //     'https://dripdome-site.s3.us-east-2.amazonaws.com/PHOTOSHOOTS/p10.jpeg',
  //   ],
  // },
  {
    category: 'SET DESIGN',
    images: [
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_1.JPG',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_2.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_3.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_4.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_5.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_6.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_7.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_8.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_9.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_10.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_11.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_12.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_13.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_14.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_15.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_16.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_17.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_18.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_19.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_20.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_21.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_22.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_23.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_24.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_25.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_26.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_27.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_28.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_29.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_30.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_31.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_32.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_33.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_34.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_35.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_36.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_37.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_38.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_39.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_40.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_41.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_42.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_43.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_44.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_45.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_46.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_47.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_48.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_49.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_50.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_51.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_52.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_53.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_54.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_55.jpeg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_56.jpg',
      'https://dripdome-site.s3.us-east-2.amazonaws.com/SETDESIGN/sd_58.png',
    ],
  },
];
